apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "pipeline-simple-app-rollout.fullname" . }}
  labels:
    {{- include "pipeline-simple-app-rollout.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }} 
{{- end }}
  selector:
    matchLabels:
      app: {{ template "pipeline-simple-app-rollout.name" . }}
      release: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: {{ template "pipeline-simple-app-rollout.fullname" . }}
      previewService: {{ template "pipeline-simple-app-rollout.fullname" . }}-preview
  template:
    metadata:
      labels:
        app: {{ template "pipeline-simple-app-rollout.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
